FROM node:20-alpine
WORKDIR /home/node/app
COPY package*.json ./
RUN npm install && npm install -g nexe@3.3.7
COPY --from=vexorian/dizquetv:nexecache /var/nexe/* /var/nexe/
COPY . .
RUN cd client && npm install